class Location {
  final int id;
  final String name;
  final String address;
  final String description;
  int countStar;
  bool isStarred;
  final String imageUrl;
  final String continent;
  final String? type; // 'food', 'things_to_do', 'places_to_stay', 'guides_tips', 'culture', 'inspiration', 'city'

  Location({
    required this.id,
    required this.name,
    required this.address,
    required this.description,
    required this.countStar,
    required this.imageUrl,
    required this.continent,
    this.isStarred = false,
    this.type,
  });

  Location copyWith({
    int? id,
    String? name,
    String? address,
    String? description,
    int? countStar,
    bool? isStarred,
    String? imageUrl,
    String? continent,
    String? type,
  }) {
    return Location(
      id: id ?? this.id,
      name: name ?? this.name,
      address: address ?? this.address,
      description: description ?? this.description,
      countStar: countStar ?? this.countStar,
      isStarred: isStarred ?? this.isStarred,
      imageUrl: imageUrl ?? this.imageUrl,
      continent: continent ?? this.continent,
      type: type ?? this.type,
    );
  }

  static final List<Location> sampleLocations = [
    // --- San Francisco Main ---
    Location(
      id: 100,
      name: 'San Francisco',
      address: 'California, USA',
      description: 'The cultural, commercial, and financial center of Northern California.',
      countStar: 500,
      imageUrl: 'assets/img_1.png',
      continent: 'america',
      type: 'city',
    ),
    
    // --- Tokyo Main ---
    Location(
      id: 200,
      name: 'Tokyo',
      address: 'Tokyo, Japan',
      description: 'A bustling metropolis combining modern tech and ancient tradition.',
      countStar: 450,
      imageUrl: 'assets/img_2.png',
      continent: 'asia',
      type: 'city',
    ),
    
    // --- Paris Main ---
    Location(
      id: 300,
      name: 'Paris',
      address: 'Paris, France',
      description: 'The city of light, famous for its art, fashion, and monuments.',
      countStar: 480,
      imageUrl: 'assets/img.png',
      continent: 'europe',
      type: 'city',
    ),
    
    // --- Cape Town Main ---
    Location(
      id: 400,
      name: 'Cape Town',
      address: 'Cape Town, South Africa',
      description: 'A coastal city in South Africa, known for its harbor and Table Mountain.',
      countStar: 320,
      imageUrl: 'assets/img_3.png',
      continent: 'africa',
      type: 'city',
    ),
    
    // --- Sydney Main ---
    Location(
      id: 500,
      name: 'Sydney',
      address: 'Sydney, Australia',
      description: 'Australia’s largest city, famous for its Opera House and harbor.',
      countStar: 390,
      imageUrl: 'assets/img_1.png',
      continent: 'oceania',
      type: 'city',
    ),

    // --- San Francisco Content ---
    Location(
      id: 101,
      name: 'The Best Restaurants in San Francisco',
      address: 'San Francisco, USA',
      description: 'Discover the top culinary spots in the City by the Bay.',
      countStar: 88,
      imageUrl: 'assets/img_1.png',
      continent: 'america',
      type: 'food',
    ),
    Location(
      id: 111,
      name: 'The Best Nightlife in San Francisco',
      address: 'San Francisco, USA',
      description: 'Where to go for drinks, dancing, and late-night fun.',
      countStar: 67,
      imageUrl: 'assets/img_2.png',
      continent: 'america',
      type: 'food',
    ),
    Location(
      id: 102,
      name: 'Top 10 Things to Do Along The Embarcadero',
      address: 'San Francisco, USA',
      description: 'The Embarcadero offers some of the best views and activities.',
      countStar: 92,
      imageUrl: 'assets/img_2.png',
      continent: 'america',
      type: 'things_to_do',
    ),
    Location(
      id: 112,
      name: 'San Francisco’s Best Bike Path: 21 Quiet Miles',
      address: 'San Francisco, USA',
      description: 'A scenic ride through the city\'s most beautiful areas.',
      countStar: 54,
      imageUrl: 'assets/img_3.png',
      continent: 'america',
      type: 'things_to_do',
    ),
    Location(
      id: 103,
      name: 'The Best Cheap Hotels to Book in San Francisco',
      address: 'San Francisco, USA',
      description: 'Budget-friendly stays without compromising on quality.',
      countStar: 75,
      imageUrl: 'assets/img.png',
      continent: 'america',
      type: 'places_to_stay',
    ),
    Location(
      id: 113,
      name: 'The Best Boutique Hotels in San Francisco',
      address: 'San Francisco, USA',
      description: 'Unique and stylish accommodations for a memorable stay.',
      countStar: 81,
      imageUrl: 'assets/img_1.png',
      continent: 'america',
      type: 'places_to_stay',
    ),
    Location(
      id: 114,
      name: 'How to Spend 24 Hours in San Francisco',
      address: 'San Francisco, USA',
      description: 'The perfect itinerary for a quick trip to the city.',
      countStar: 110,
      imageUrl: 'assets/img_2.png',
      continent: 'america',
      type: 'guides_tips',
    ),
    Location(
      id: 115,
      name: 'The 10 Must-Visit Neighborhoods',
      address: 'San Francisco, USA',
      description: 'From Mission to Marina, explore the city\'s diverse areas.',
      countStar: 95,
      imageUrl: 'assets/img_3.png',
      continent: 'america',
      type: 'guides_tips',
    ),
    Location(
      id: 104,
      name: 'Must-See Artworks at The de Young Museum',
      address: 'San Francisco, USA',
      description: 'A guide to the most iconic pieces in Golden Gate Park.',
      countStar: 82,
      imageUrl: 'assets/img_3.png',
      continent: 'america',
      type: 'culture',
    ),
    Location(
      id: 116,
      name: 'The Castro: San Francisco\'s Historic District',
      address: 'San Francisco, USA',
      description: 'Discover the rich history and culture of the LGBTQ+ landmark.',
      countStar: 134,
      imageUrl: 'assets/img.png',
      continent: 'america',
      type: 'culture',
    ),
    Location(
      id: 105,
      name: 'The 9 Best Things to See and Do in SoMa',
      address: 'San Francisco, USA',
      description: 'Exploring the vibrant South of Market neighborhood.',
      countStar: 85,
      imageUrl: 'assets/img_1.png',
      continent: 'america',
      type: 'inspiration',
    ),
    Location(
      id: 117,
      name: 'Top 10 Things to Do in Mission District',
      address: 'San Francisco, USA',
      description: 'Murals, tacos, and sunshine in the heart of the city.',
      countStar: 78,
      imageUrl: 'assets/img_2.png',
      continent: 'america',
      type: 'inspiration',
    ),

    // --- Tokyo Content ---
    Location(
      id: 201,
      name: 'Hidden Sushi Gems in Tokyo',
      address: 'Tokyo, Japan',
      description: 'The best omakase experiences off the beaten path.',
      countStar: 150,
      imageUrl: 'assets/img_2.png',
      continent: 'asia',
      type: 'food',
    ),
    Location(
      id: 202,
      name: 'Walking Through Akihabara Electric Town',
      address: 'Tokyo, Japan',
      description: 'Anime, gadgets, and neon lights.',
      countStar: 200,
      imageUrl: 'assets/img_1.png',
      continent: 'asia',
      type: 'things_to_do',
    ),
    Location(
      id: 203,
      name: 'Traditional Ryokans with Modern Comfort',
      address: 'Tokyo, Japan',
      description: 'Experience authentic Japanese hospitality.',
      countStar: 95,
      imageUrl: 'assets/img.png',
      continent: 'asia',
      type: 'places_to_stay',
    ),
    Location(
      id: 204,
      name: 'Tokyo Subway Master Guide',
      address: 'Tokyo, Japan',
      description: 'Navigating the world\'s most complex rail system.',
      countStar: 120,
      imageUrl: 'assets/img_3.png',
      continent: 'asia',
      type: 'guides_tips',
    ),
    Location(
      id: 205,
      name: 'The History of Sensō-ji Temple',
      address: 'Tokyo, Japan',
      description: 'Asakusa\'s most iconic cultural landmark.',
      countStar: 180,
      imageUrl: 'assets/img_2.png',
      continent: 'asia',
      type: 'culture',
    ),
    Location(
      id: 206,
      name: 'Cherry Blossom Viewing Spots',
      address: 'Tokyo, Japan',
      description: 'Where to find the most beautiful blooms.',
      countStar: 250,
      imageUrl: 'assets/img_1.png',
      continent: 'asia',
      type: 'inspiration',
    ),

    // --- Paris Content ---
    Location(
      id: 301,
      name: 'Best Boulangeries in Paris',
      address: 'Paris, France',
      description: 'Where to find the perfect croissant.',
      countStar: 140,
      imageUrl: 'assets/img.png',
      continent: 'europe',
      type: 'food',
    ),
    Location(
      id: 302,
      name: 'Sunset at Montmartre',
      address: 'Paris, France',
      description: 'The best view of the city of love.',
      countStar: 220,
      imageUrl: 'assets/img_3.png',
      continent: 'europe',
      type: 'things_to_do',
    ),
    Location(
      id: 303,
      name: 'Charming Boutique Hotels in Le Marais',
      address: 'Paris, France',
      description: 'Stay in the heart of historic Paris.',
      countStar: 110,
      imageUrl: 'assets/img_1.png',
      continent: 'europe',
      type: 'places_to_stay',
    ),
    Location(
      id: 304,
      name: 'Paris Museum Pass: Is it Worth It?',
      address: 'Paris, France',
      description: 'A complete guide to saving on sights.',
      countStar: 85,
      imageUrl: 'assets/img_2.png',
      continent: 'europe',
      type: 'guides_tips',
    ),
    Location(
      id: 305,
      name: 'Secrets of the Louvre Museum',
      address: 'Paris, France',
      description: 'Masterpieces beyond the Mona Lisa.',
      countStar: 190,
      imageUrl: 'assets/img.png',
      continent: 'europe',
      type: 'culture',
    ),
    Location(
      id: 306,
      name: 'A Weekend in the Loire Valley',
      address: 'Paris, France',
      description: 'Castle hopping near the capital.',
      countStar: 130,
      imageUrl: 'assets/img_3.png',
      continent: 'europe',
      type: 'inspiration',
    ),

    // --- Cape Town Content ---
    Location(
      id: 401,
      name: 'Wine Tasting in Stellenbosch',
      address: 'Cape Town, South Africa',
      description: 'Exquisite vineyards just outside the city.',
      countStar: 105,
      imageUrl: 'assets/img_3.png',
      continent: 'africa',
      type: 'food',
    ),
    Location(
      id: 402,
      name: 'Hiking Table Mountain',
      address: 'Cape Town, South Africa',
      description: 'Multiple routes for every fitness level.',
      countStar: 180,
      imageUrl: 'assets/img_2.png',
      continent: 'africa',
      type: 'things_to_do',
    ),
    Location(
      id: 403,
      name: 'Luxury Camps Bay Villas',
      address: 'Cape Town, South Africa',
      description: 'Beachfront living with stunning sunsets.',
      countStar: 70,
      imageUrl: 'assets/img_1.png',
      continent: 'africa',
      type: 'places_to_stay',
    ),
    Location(
      id: 404,
      name: 'Safety Tips for Cape Town',
      address: 'Cape Town, South Africa',
      description: 'Practical advice for a worry-free trip.',
      countStar: 90,
      imageUrl: 'assets/img.png',
      continent: 'africa',
      type: 'guides_tips',
    ),
    Location(
      id: 405,
      name: 'District Six Museum History',
      address: 'Cape Town, South Africa',
      description: 'A moving look at South Africa\'s past.',
      countStar: 115,
      imageUrl: 'assets/img_3.png',
      continent: 'africa',
      type: 'culture',
    ),
    Location(
      id: 406,
      name: 'Road Trip to Cape Point',
      address: 'Cape Town, South Africa',
      description: 'Wildlife and wild oceans at the edge of the world.',
      countStar: 160,
      imageUrl: 'assets/img_2.png',
      continent: 'africa',
      type: 'inspiration',
    ),

    // --- Sydney Content ---
    Location(
      id: 501,
      name: 'Fresh Seafood at Sydney Fish Market',
      address: 'Sydney, Australia',
      description: 'The best catch in the Southern Hemisphere.',
      countStar: 125,
      imageUrl: 'assets/img_1.png',
      continent: 'oceania',
      type: 'food',
    ),
    Location(
      id: 502,
      name: 'Bondi to Coogee Coastal Walk',
      address: 'Sydney, Australia',
      description: 'Breathtaking ocean views and hidden coves.',
      countStar: 210,
      imageUrl: 'assets/img_2.png',
      continent: 'oceania',
      type: 'things_to_do',
    ),
    Location(
      id: 503,
      name: 'Harbor View Hotels in the Rocks',
      address: 'Sydney, Australia',
      description: 'Wake up to the Opera House.',
      countStar: 80,
      imageUrl: 'assets/img.png',
      continent: 'oceania',
      type: 'places_to_stay',
    ),
    Location(
      id: 504,
      name: 'Sydney Ferry Guide',
      address: 'Sydney, Australia',
      description: 'The most scenic way to commute.',
      countStar: 100,
      imageUrl: 'assets/img_3.png',
      continent: 'oceania',
      type: 'guides_tips',
    ),
    Location(
      id: 505,
      name: 'Aboriginal Heritage in Sydney',
      address: 'Sydney, Australia',
      description: 'The ancient stories of the Gadigal people.',
      countStar: 145,
      imageUrl: 'assets/img_1.png',
      continent: 'oceania',
      type: 'culture',
    ),
    Location(
      id: 506,
      name: 'Day Trip to Blue Mountains',
      address: 'Sydney, Australia',
      description: 'Echo Point and the Three Sisters.',
      countStar: 175,
      imageUrl: 'assets/img_2.png',
      continent: 'oceania',
      type: 'inspiration',
    ),
    
    // --- Original sample locations ---
    Location(
      id: 1,
      name: 'Oeschinen Lake Campground',
      address: 'Kandersteg, Switzerland',
      description: 'Lake Oeschinen lies at the foot of the Blüemlisalp.',
      countStar: 41,
      imageUrl: 'assets/img_1.png',
      continent: 'europe',
    ),
    Location(
      id: 3,
      name: 'Ha Long Bay',
      address: 'Quang Ninh, Vietnam',
      description: 'A UNESCO World Heritage site.',
      countStar: 98,
      imageUrl: 'assets/img_2.png',
      continent: 'asia',
    ),
  ];
}
