// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCzM0ONEMkOT51o3xo3hqvGH2ADfspz3I',
    appId: '1:145029146404:web:56c0e9546cc44fc732f5b1',
    messagingSenderId: '145029146404',
    projectId: 'prm393-group3-a48cf',
    authDomain: 'prm393-group3-a48cf.firebaseapp.com',
    storageBucket: 'prm393-group3-a48cf.firebasestorage.app',
    measurementId: 'G-E7Y0744HSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmubSlRwicW5UhKIs_46grNth5VQwQn58',
    appId: '1:145029146404:android:8231964bd311152332f5b1',
    messagingSenderId: '145029146404',
    projectId: 'prm393-group3-a48cf',
    storageBucket: 'prm393-group3-a48cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnA9vt9t8sgHVu0-XCCdzgGNN9fKdeVsc',
    appId: '1:145029146404:ios:1fea8c617e71e2b232f5b1',
    messagingSenderId: '145029146404',
    projectId: 'prm393-group3-a48cf',
    storageBucket: 'prm393-group3-a48cf.firebasestorage.app',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnA9vt9t8sgHVu0-XCCdzgGNN9fKdeVsc',
    appId: '1:145029146404:ios:1fea8c617e71e2b232f5b1',
    messagingSenderId: '145029146404',
    projectId: 'prm393-group3-a48cf',
    storageBucket: 'prm393-group3-a48cf.firebasestorage.app',
    iosBundleId: 'com.example.lab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCzM0ONEMkOT51o3xo3hqvGH2ADfspz3I',
    appId: '1:145029146404:web:b7a5d931104012f532f5b1',
    messagingSenderId: '145029146404',
    projectId: 'prm393-group3-a48cf',
    authDomain: 'prm393-group3-a48cf.firebaseapp.com',
    storageBucket: 'prm393-group3-a48cf.firebasestorage.app',
    measurementId: 'G-SXY61TM6J7',
  );
}
